# -*- encoding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2012 Tiny SPRL (http://tiny.be). All Rights Reserved
#
#    This module,
#    Copyright (C) 2015 Jordi Llinares López - bigandopen@bigandopen.com
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see http://www.gnu.org/licenses/.
#
##############################################################################

{
    'name': 'MRP Manual consume/production',
    'version': '1.0',
    'author': 'KM Sistemas de información, S.L.',
    'category': '',
    'summary': 'Manual and independent consume/production in manufacturing.',
    'complexity': 'easy',
    'description' : """This module implements some changes on the base 'mrp' module of Odoo:
    
-   Invalidates default production wizard and, more specifically, 'action_produce'. We won't
    'consume' or 'consume and produce' anymore. Instead, consume and produce operations are
    independent and manual: 
        -   For each 'to consume' move a button and a wizard is shown. Small changes over the
            original.
        -   For each 'to produce' move, a button and a wizard is shown. A new wizard
            'stock.move.produce' is developed and linked through a button each 'to produce' move.
            This wizard works the same way that stock.move.consume, allowing to manually enter
            each production batch. A lot number can easily be generated by pressing a button from
            within the wizard, for products with production tracking enabled and lot creation
            mode set to 'auto'.
        -   The order's 'Produce' button is replaced by a 'Close order' button that warns
            you if the order has any pending consumption/production moves (it lets you close
            the order, though).
    When you have consumed/produced all you needed to, you'll 'Close order'. If there are any
    pending moves, a warning is raised (though it lets you close the order). Counterpart of this
    warning is that the page header now uses double height.

-   'Consumed' and 'Produced' fields are not showing cancelled moves anymore.

-   Displays the real produced quantity of order's product on the order form header, below the ordered
    quantity.

""",
    'website': 'http://www.kmsistemas.com',
    'depends': [
        'product',
        'mrp',
        'stock',
        'stock_lot_enh_base',
    ],
    'conflicts': [
    ],
    'data': [
        # Workflows
        'workflow/mrp_workflow.xml',

        # Views
        'views/mrp_consume_produce_views.xml',
        'views/mrp_view.xml',
    ],
    'qweb': [
    ],
    'demo': [
    ],
    'test': [
    ],
    'installable': True,
    'auto_install': False,
}
